### ISSUE TITLE
Are the logs sent asynchronously

### ISSUE THREAD

**Issue by gauravmak** [Pod-Point/laravel-monolog-kinesis#13]
Hi,

Thanks for making this.

Can this slow down the app? And what if the AWS is down for a bit?

**Comment by clemblanco** [comment]
Hey @gauravmak,

Good question. I don't think Monolog is logging things asynchronously by default. You'd need to queue Jobs and have workers to process these, etc... in order to do this asynchronously.

Logging doesn't have a serious influence on performances, especially when you are using something like Kineses which is designed to receive high volumes of such transactions.
Monolog handlers are like instances of objects for data handling and storing behaviours.

This generally is using pretty standard Laravel/Monolog stuff.

At the moment [we fail silently](https://github.com/Pod-Point/laravel-monolog-kinesis/blob/3a7a2f509e167b705190b8b17af16af1b96fa483/src/Handler.php#L45-L49) if for whatever reason AWS is not available but maybe we could look at offering some other approach... What would you recommend?

We usually always use this on top of the standard `daily` Laravel logging channel so we would still have the log message on the daily files themselves. If we were not failing silently, you would start seeing errors coming to you to Sentry/Rollbar/etc... for example.

Could maybe add something like:

```php
<?php

return [

    // ...
    
    'channels' => [
    
        'some_channel' => [
            'driver' => 'kinesis',
            // ...
            'fail_silently' => false,
        ],

    ],

];
```

See what [Monolog ElasticsearchHandler](https://github.com/Seldaek/monolog/blob/fb2c324c17941ffe805aa7c953895af96840d0c9/src/Monolog/Handler/ElasticsearchHandler.php#L152-L154) does for example.

**Comment by gauravmak** [comment]
Three options that I can think of:

1) Use Monolog's BufferHandler in combination with fastcgi_finish_request as per [this comment](https://github.com/maxbanton/cwh/issues/25#issuecomment-353573180) (Only for nginx + PHP FPM)

2) Use sysout in combination with [CloudWatch agent](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/install-CloudWatch-Agent-on-EC2-Instance.html)

3) PR to Laravel for logging stuff using Monolog inside terminable middleware of something so that we do not need to worry anything about it at all 😄


Closing this issue, for now, thanks.
